# Generated by Django 3.2.9 on 2021-12-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspirations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.ManyToManyField(blank=True, to='inspirations.Message'),
        ),
    ]
